add options for VIT pruning support
Nota-NetsPresso/PyNP-python-package pull request #16
Opened 2023-07-28 04:49 UTC by Only-bottle

Added options for VIT pruning support.

### Example
```
COMPRESSED_MODEL_NAME = "test_l2norm"
COMPRESSION_METHOD = CompressionMethod.PR_L2
RECOMMENDATION_METHOD = RecommendationMethod.SLAMP
RECOMMENDATION_RATIO = 0.5
OUTPUT_PATH = "./graphmodule_recommend.pt"
OPTIONS = Options(
    policy=Policy.AVERAGE, layer_norm=LayerNorm.TSS_NORM, group_policy=GroupPolicy.COUNT, reshape_channel_axis=-1
)
compressed_model = compressor.recommendation_compression(
    model_id=model.model_id,
    model_name=COMPRESSED_MODEL_NAME,
    compression_method=COMPRESSION_METHOD,
    recommendation_method=RECOMMENDATION_METHOD,
    recommendation_ratio=RECOMMENDATION_RATIO,
    options=OPTIONS,
    output_path=OUTPUT_PATH,
)
```

2023-07-31 04:38 UTC, paran3 approved these changes
👍

2023-08-02 07:16 UTC, Youngwhy requested changes

2023-08-02 07:16 UTC, Youngwhy commented on netspresso/compressor/client/utils/enum.py
> +class Policy(str, Enum):
Enum클래스를 선언해서 사용하는 과정에서 각 enum을 Literal로 만드는 방법이 중복되어 있어고 하드코딩이 되어있어서 아래와 같이 상속을 사용하면 오류를 줄일 수 있을 것 같습니다.

```
class MyEnumBase(str, Enum):
    @classmethod
    def to_list(cls):
        return [item.value for item in cls]


class Policy(MyEnumBase):
    SUM = "sum"
    AVERAGE = "average"
    COUNT = "count"
    NONE = "none"
```

2023-08-02 07:29 UTC, Only-bottle commented on netspresso/compressor/client/utils/enum.py
> +class Policy(str, Enum):
아 이 부분은 예전 PR에서 태민님하고도 얘기 나눴던 건데,
Literal의 경우 정적으로 타입을 지정하는 기능을 가지고 있어서, 동적으로 처리하기 힘들어요.
(테스트 했을 때 동적으로 해도 실행에 문제는 없었어요.)
코드상으로 깔끔할 수 있는데 문법상 맞지 않아서 사용하지 않기로 했어요

2023-08-02 08:20 UTC, Youngwhy commented on netspresso/compressor/client/utils/enum.py
> +class Policy(str, Enum):
아하 동적으로 처리가 안되는군요 알겟습니다!

2023-08-02 08:20 UTC, Youngwhy approved these changes

2023-08-06 02:11 UTC, SanggeonPark approved these changes

2023-08-07 01:25 UTC, merged